//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Control_001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int Cod_cli { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Correo { get; set; }
        public int Cod_ciudad { get; set; }
        public int Cod_pais { get; set; }
        public int Cod_compra { get; set; }
        public int Cod_estado { get; set; }
        public string Id_cli { get; set; }
        public string Red_Social { get; set; }
        public string Edad { get; set; }
    
        public virtual Ciudades Ciudades { get; set; }
        public virtual Compras Compras { get; set; }
        public virtual Paises Paises { get; set; }
    }
}
