//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Control_001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public Compras()
        {
            this.Clientes = new HashSet<Clientes>();
        }
    
        public int Cod_compra { get; set; }
        public int Cod_cli { get; set; }
        public int Cod_empresa { get; set; }
        public int Fecha_compra { get; set; }
    
        public virtual ICollection<Clientes> Clientes { get; set; }
        public virtual Empresas Empresas { get; set; }
    }
}
