//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Control_001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas
    {
        public Empresas()
        {
            this.Compras = new HashSet<Compras>();
        }
    
        public int Cod_empresa { get; set; }
        public int Cod_actividad { get; set; }
        public int Cod_estado { get; set; }
        public int Cod_pais { get; set; }
        public int Cod_ciudad { get; set; }
    
        public virtual Ciudades Ciudades { get; set; }
        public virtual ICollection<Compras> Compras { get; set; }
        public virtual Paises Paises { get; set; }
    }
}
