//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Control_001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa_detalle
    {
        public int Cod_empresa { get; set; }
        public string Nombre_empresa { get; set; }
        public string Direccion_empresa { get; set; }
        public int Telefono_empresa { get; set; }
    }
}
