//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Control_001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paises
    {
        public Paises()
        {
            this.Clientes = new HashSet<Clientes>();
            this.Empresas = new HashSet<Empresas>();
            this.Promociones = new HashSet<Promociones>();
        }
    
        public int Cod_pais { get; set; }
        public string Nombre_pais { get; set; }
    
        public virtual ICollection<Clientes> Clientes { get; set; }
        public virtual ICollection<Empresas> Empresas { get; set; }
        public virtual ICollection<Promociones> Promociones { get; set; }
    }
}
